### PR TITLE
chapter 1

### PR DESCRIPTION
**Pull request by mvansan**
Q1: Co nhung cach nao de tao 1 project Laravel?
A: Co nhung cach sau de tao 1 project Laravel:
1. Su dung Composer:
 - Cai dat Composer
 - Chay cau lenh "composer create-project --prefer-dist laravel/laravel project_name" de tao project 
2. Su dung Laravel Installer va Composer
 - Cai dat Composer
 - Cai dat Laravel: composer global require laravel/installer
 - Cai dat project bang Laravel Installer: laravel new project_name
 
Q2: Neu muc dich chinh, ngan gon cua cac thu muc trong du an:
A: Cac muc dich cua cac thu muc trong du an:
 - app: Chua cac core source code cua ung dung, bao gom cac models, controllers va service provider
 - bootstrap: Noi laravel duoc khoi tao, thiet lap bootstrap
 - config: Cai dat tuy chinh he thong
 - database: Quan ly database
 - public: Chua file index.php
 - resources: Chua cac file chua complile cua ung dung, bao gom view, cac tep assets
 - routes: Chua cac file dinh nghia route cua ung dung
 - storage: Chua cac file da duoc compiled, session, logs,..
 - tests: Chua cac file kiem thu he thong
 - vendor: Chua cac goi thu vien phu thuoc cua Composer
 
 Q: Vong doi cua 1 request trong Laravel?
A:
1. First Steps: Moi request se duoc chuyen den tep 'public/index.php', noi khoi dong framework Laravel 
   bang cach tai autoloader cua Composer va khoi tao ung dung tu 'bootstrap/app.php'.
2. HTTP/Console Kernel: Request duoc gui den HTTP Kernel qua phuc thuc 'handle' cua kernel.
   HTTP kernel xu ly request thong qua cac bootstrap va middleware
3. Service Provider: Service provider duoc load va khoi dong, cau hinh cac thanh phan quan trong cua framework
4. Routing: Request duoc chuyen den router de xac dinh route hoac controllers xu ly. 
   Cac middleware cu the cua route cung duoc thuc hien o day.
5. Finish: Response tu route hoac controllers duoc gui lai qua chuoi middleware truoc khi tra ve web brower cua user

### CODE REVIEW

**Comment by mvansan** [comment]
Ready

**Comment by mvansan** [comment]
Ready

**Comment by mvansan** [comment]
ready

**Comment by mvansan** [comment]
Ready

**Comment by ghost** [comment]
ready

**Review by ghost — APPROVED** [review]

**Pull request merged**
